// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"navbar-menu p-5\"><div class=\"navbar-start is-size-1 is-underlined\"><a class=\"navbar-item\" hx-post=\"/body/\" hx-target=\"#mainBody\">RECIPES</a></div><div class=\"navbar-end\"><div class=\"navbar-item\"><div class=\"control\"><button class=\"button\" hx-post=\"/random-meal/\" hx-target=\"#mainBody\" type=\"button\">Random</button></div><div class=\"control\"><input id=\"search-input\" class=\"input\" type=\"text\" placeholder=\"Search Recipe\" hx-post=\"/search-meal/\" hx-target=\"#mainBody\" hx-trigger=\"keyup[key==&#39;Enter&#39;]\"></div><div class=\"control\"><button class=\"button\" hx-post=\"/search-meal/\" hx-target=\"#mainBody\" hx-trigger=\"click\" hx-include=\"#search-input\">Search</button></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
